import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  connectDB,
  connectPostgres,
  disconnectDB,
  disconnectPostgres,
} from '@/config'
import { config } from '@/config'
import { KbEntry, reindexKnowledgeBase } from '@/services/ai/kb.service'
import logger from '@/utils/logger'

/**
 * Rebuild the support knowledge base from the command line.
 *
 * Mongo is needed as well as Postgres: the corpus includes a chunk per study
 * document, so the content collection has to be readable. Redis is not, which
 * is why it is not connected here.
 *
 * Run this after editing src/services/ai/kb/support.md, after changing a level
 * or badge, and after a content import. Nothing reindexes on its own.
 */
/**
 * Write a readable list of everything now in the vector store.
 *
 * The corpus is three sources and only one of them is a file a person edits,
 * so without this there is no way to see what the assistant can actually
 * answer from short of querying Postgres. Written from the same array that
 * was just inserted, so it cannot describe a state the database is not in.
 *
 * Written by the CLI rather than by the service: the admin reindex route runs
 * inside a container with a read only checkout, where there is nowhere useful
 * to put it.
 */
const writeInventory = (index: KbEntry[]) => {
  const path = join(
    __dirname,
    '..',
    '..',
    'services',
    'ai',
    'kb',
    'KB-CONTENTS.md'
  )

  const rows = (source: string) =>
    index
      .filter((entry) => entry.source === source)
      .map(
        (entry) =>
          `| ${entry.heading ?? '(none)'} | ${entry.sourceId ?? '-'} | ${entry.characters} |`
      )
      .join('\n')

  const table = (title: string, note: string, source: string) => {
    const body = rows(source)
    return body === ''
      ? `## ${title}\n\n${note}\n\nNothing indexed from this source.\n`
      : `## ${title}\n\n${note}\n\n| PASSAGE | SOURCE ID | CHARACTERS |\n| ------- | --------- | ---------- |\n${body}\n`
  }

  const contents = [
    '# KNOWLEDGE BASE CONTENTS',
    '',
    'Every passage the support assistant can retrieve. Generated by',
    '`npm run ai:reindex`, so it describes the database as of the last run.',
    'Do not edit it by hand.',
    '',
    'The assistant answers only from these passages. Anything not listed here',
    'it does not know, and it is instructed to refer the person to',
    'studzee247@gmail.com rather than guess.',
    '',
    `Total passages: ${index.length}`,
    '',
    table(
      'HELP MATERIAL',
      'One passage per `##` section of `support.md`, which is the file to ' +
        'edit when the assistant should know something new about the app.',
      'support-md'
    ),
    '',
    table(
      'REGISTRIES',
      'Generated from the code constants in `src/models/gamification.ts` and ' +
        '`src/models/topics.ts` at index time, so the ladder, the badges and ' +
        'the topic list cannot fall out of date in prose.',
      'registry'
    ),
    '',
    table(
      'STUDY MATERIAL',
      'One passage per document in the content collection, built from its ' +
        'title, summary and key notes. This is what lets the assistant point ' +
        'someone at the right material, and the source id is the document a ' +
        'cited source links to in the app.',
      'content'
    ),
  ].join('\n')

  writeFileSync(path, contents, 'utf8')
  logger.info(
    { path, passages: index.length },
    'Wrote the knowledge base inventory'
  )
}

const run = async () => {
  if (!config.AI_ENABLED) {
    logger.error(
      'AI_ENABLED is false, so there is no embedding endpoint to call. ' +
        'Set AI_ENABLED=true and AI_API_KEY before reindexing.'
    )
    process.exit(1)
  }

  logger.info('Connecting to databases...')
  await connectDB()
  await connectPostgres()

  logger.info(
    { model: config.AI_EMBED_MODEL, dimensions: config.AI_EMBED_DIM },
    'Rebuilding the support knowledge base...'
  )
  const result = await reindexKnowledgeBase()

  logger.info('Disconnecting from databases...')
  await disconnectDB()
  await disconnectPostgres()

  writeInventory(result.index)

  logger.info(result, 'Reindex finished.')
  process.exit(0)
}

run().catch((error) => {
  logger.error(error, 'Reindex failed')
  process.exit(1)
})
