org: agent
app: content-gen-ai
service: content-generation-api

provider:
  name: aws
  runtime: python3.12

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 minute)
